# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          范清宇的博客
paginate:       5
baseurl:        ""
url:            "https://vanqingyu.github.io/tale"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         范清宇
  url:          https://vanqingyu.github.io
  email:        vanqingyu@163.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
